//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskmgr.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int IdStaff { get; set; }
        public string NameStaff { get; set; }
        public string SurnameStaff { get; set; }
        public string MiddleNameStaff { get; set; }
        public string TaskStaff { get; set; }
        public string StatusTaskStaff { get; set; }
    }
}
